# Whether to ignore frontmatter at the beginning of HAML documents for
# frameworks such as Jekyll/Middleman
skip_frontmatter: false

linters:
  LineLength:
    enabled: true
    max: 160
  RuboCop:
    enabled: false
