# Application configuration

default: &default
  title: "Magestil"
  description: "Cursos Profissionais de Nível 4"
  url: "https://www.magestil.pt/"
  twitter_username: "@magensinus"

development:
  <<: *default
  environment: "development"

test:
  <<: *default
  environment: "test"

production:
  <<: *default
  environment: "production"
